FROM ubuntu

# Set the Current Working Directory inside the container
WORKDIR mkdir opt

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Expose port 8080 to the outside world
EXPOSE 8080
